on:
  schedule:
    - cron: '0 0,12 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: Ash258/Scoop-GithubActions@stable

