on:
  schedule:
    - cron: '0 0/6 * * *'

name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: shovel-org/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'
